# Generated by Django 5.2.12 on 2026-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-tag', help_text='Font Awesome class, ví dụ: fa-solid fa-laptop', max_length=100),
        ),
    ]
