# Generated by Django 5.2.12 on 2026-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa thanh toán'), ('paid', 'Đã thanh toán - chờ giao hàng'), ('shipping', 'Đang giao'), ('done', 'Đã giao')], default='pending', max_length=20),
        ),
    ]
